'''
Created on 01 feb 2019

@author: Matteo
'''
samsung_mappings = {
                    "yellow":"KEY_YELLOW",
                    "red":"KEY_RED",
                    "blue":"KEY_CYAN",
                    "green":"KEY_GREEN",
                    "power":"KEY_POWEROFF",
                    "0":"KEY_0",
                    "1":"KEY_1",
                    "2":"KEY_2",
                    "3":"KEY_3",
                    "4":"KEY_4",
                    "5":"KEY_5",
                    "6":"KEY_6",
                    "7":"KEY_7",
                    "8":"KEY_8",
                    "9":"KEY_9",
                    "up":"KEY_UP",
                    "down":"KEY_DOWN",
                    "left":"KEY_LEFT",
                    "right":"KEY_RIGHT",
                    "volume+":"KEY_VOLUP",
                    "volume-":"KEY_VOLDOWN",
                    "ttx":"KEY_TTX_MIX",
                    "revw":"KEY_REWIND",
                    "stop":"KEY_STOP",
                    "play":"KEY_PLAY",
                    "pause":"KEY_PAUSE",
                    "ffw":"KEY_FF",
                    "exit":"KEY_RETURN",
                    "back":"KEY_PRECH",
                    "chlist":"KEY_CH_LIST",
                    "ok":"KEY_ENTER",
                    "mute":"KEY_MUTE",
                    "menu":"KEY_MENU",
                    "info":"KEY_INFO",
                    "rec":"KEY_REC",
                    "tools":"KEY_TOOLS",
                    "av":"KEY_SOURCE",
                    "programma+":"KEY_CHUP",
                    "programma-":"KEY_CHDOWN",
                    }